// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0Pinby80ckqf_B3jngWTddOwTZSMKMg',
    appId: '1:238384657279:web:a507960ad0993d97dba04a',
    messagingSenderId: '238384657279',
    projectId: 'egg-mobile',
    authDomain: 'egg-mobile.firebaseapp.com',
    storageBucket: 'egg-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQ3-Dvdqp6jNvzx01A0YF_elLdQzaC8o',
    appId: '1:238384657279:android:aa84b165df8c6dd3dba04a',
    messagingSenderId: '238384657279',
    projectId: 'egg-mobile',
    storageBucket: 'egg-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxtQkWKbf2yNdsW5fzQY9ykJP2BUuYbsc',
    appId: '1:238384657279:ios:b6670c9a1002d7d5dba04a',
    messagingSenderId: '238384657279',
    projectId: 'egg-mobile',
    storageBucket: 'egg-mobile.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxtQkWKbf2yNdsW5fzQY9ykJP2BUuYbsc',
    appId: '1:238384657279:ios:bc9d298549a02d6adba04a',
    messagingSenderId: '238384657279',
    projectId: 'egg-mobile',
    storageBucket: 'egg-mobile.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
